/* DECLARAÇÃO DE VARIÁVEIS DE AMBIENTE PARA AS CONFIGURAÇÕES DO APP */
declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_EAS_BUILD_PROFILE: "development" | "preview" | "production";
    EXPO_PUBLIC_FACEBOOK_APP_ID: string;
    EXPO_PUBLIC_FACEBOOK_CLIENT_TOKEN: string;
    EXPO_PUBLIC_PRODUCTION_GOOGLE_ANDROID_CLIENT_ID: string;

    EXPO_PUBLIC_PRODUCTION_GOOGLE_ANDROID_CLIENT_ID: string;
    EXPO_PUBLIC_PREVIEW_GOOGLE_ANDROID_CLIENT_ID: string;
    EXPO_PUBLIC_DEVELOPMENT_GOOGLE_ANDROID_CLIENT_ID: string;
    EXPO_PUBLIC_WEB_GOOGLE_ANDROID_CLIENT_ID: string;
  }
}
