declare namespace NodeJS {
  interface ProcessEnv {
    EAS_BUILD_PROFILE: "development" | "preview" | "production";
    EXPO_PUBLIC_BACKEND_URL: string;
    EXPO_PUBLIC_PRODUCTION_GOOGLE_ANDROID_CLIENT_ID: string;
    EXPO_PUBLIC_PREVIEW_GOOGLE_ANDROID_CLIENT_ID: string;
    EXPO_PUBLIC_DEVELOPMENT_GOOGLE_ANDROID_CLIENT_ID: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: string;
    EXPO_PUBLIC_FACEBOOK_APP_ID: string;
    EXPO_PUBLIC_FACEBOOK_CLIENT_TOKEN: string;
  }
}
